server:
  port: 8094

product:
  name: producer0

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: du_java
    password: W0gefGMnHK2OOiYq

rocketmq:
  name-server: localhost:9876
  producer:
    group: producer-group0
    sendMessageTimeout: 300000

topic0: topic0