server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: gateway
        tags: version=1.0
        health-check-interval: 15s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health

management:
  endpoint:
    health:
      show-details: always