server:
  port: 8080
project:
  name: mp-demo

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db0?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis-plus:
  typeAliasesPackage: org.bomb.duapp.mp.entity
  mapperLocations: org/bomb/duapp/mp/mapper/xml/*.xml

logging:
  level:
    org.bomb.duapp.mp: debug

