# ================== 数据源参数配置 =================
initialSize: 5  # 初始化链接数量
minIdle: 5  # 最小链接池数量
maxActive: 20 # 最大链接池数量
maxWait: 60000  # 最大等待链接时常
timeBetweenEvictionRunsMillis: 60000 # 周期检测时长
minEvictableIdleTimeMillis: 300000  # 链接最大空间时长
validationQuery: SELECT 1 FROM DUAL

# ================== 数据源分片配置 ==================
sharding:
  jdbc:
    config:
      sharding:
        props:
          sql:
            show: true # 打印sql日志
        defaultDataSourceName: ds0 # 未配置分片规则的表将通过默认数据源定位-适用于单库单表，该表无需配置分片规则
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds$->{user_id % 4}
        tables:
          t_order:
            actual-data-nodes: ds$->{0..3}.t_order_000$->{0..3}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_000$->{order_id % 4}
    dataSource:
      names: ds0,ds1,ds2,ds3 # 数据源名称，多数据源以逗号分割
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db_00?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
        initialSize: ${initialSize}
        minIdle: ${minIdle}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        validationQuery: ${validationQuery}
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db_01?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
        initialSize: ${initialSize}
        minIdle: ${minIdle}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        validationQuery: ${validationQuery}
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db_02?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
        initialSize: ${initialSize}
        minIdle: ${minIdle}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        validationQuery: ${validationQuery}
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db_03?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
        initialSize: ${initialSize}
        minIdle: ${minIdle}
        maxActive: ${maxActive}
        maxWait: ${maxWait}
        validationQuery: ${validationQuery}
        timeBetweenEvictionRunsMillis: ${timeBetweenEvictionRunsMillis}
        minEvictableIdleTimeMillis: ${minEvictableIdleTimeMillis}
